spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lxoddb?useUnicode=ture&characterEncoding=utf-8
    username: root
    data-password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lexueoude.web: info
  file: log/lxodweb_pro.log
server:
  port: 8080
